### PR TITLE
Km friends list

### PR DESCRIPTION
**Pull request by kellymorin**
git checkout -b km-friendsList
git pull origin km-friendsList

When a user clicks on the friends tab in the nav bar, the page will load the profile picture and name of each of their friends, along with a delete button. When delete button is selected, an alert will show inline, asking the user to confirm they would like to delete a friend. If they select 'yes' the relationship will be deleted in the database and the DOM will reload. If they select 'no' the DOM will reload.

### CODE REVIEW

**Comment by jasehackman** [comment]
Works great!!

**Comment by braddavistech** [comment]
Looks good. 👍

**Comment by braddavistech** [comment]
Nice work. 👍

**Comment by jasehackman** [comment]
👍

**Pull request merged**
