### PR TITLE
Km friend chat

### PR DESCRIPTION
**Pull request by kellymorin**
git checkout km-friendChat
git pull origin master km-friendChat

Given an active user sees a chat message from another user
And wants to make that user a friend
When the active user clicks on the other user's name in the chat history
Then a message should be presented to the active user asking for verification of adding the other user to their friend list

### CODE REVIEW

**Comment by braddavistech** [comment]
👍 nice work!

**Comment by jasehackman** [comment]
If I click 'No' to being a friend it doesn't take me out of the pop-up. Can you set up an event listener for it to reload the messages?

This will probably be resolved later but when I click on someone who I 'assume' is already my friend nothing happens. Since I can't see my friends list it would be nice to have a message that says "already friends"

**Comment by jasehackman** [comment]
Great!

**Comment by braddavistech** [comment]
Looks good. Nice work! 👍

**Pull request merged**
