### PR TITLE
Restrict blank entries in tasks page

### PR DESCRIPTION
**Pull request by rbmccr**
git checkout test-branch

- empty fields populate back to original values in tasks
- date event is now on blur, not on change

### CODE REVIEW

**Comment by kellymorin** [comment]
👍 Looks great!

**Comment by jasehackman** [comment]
If you click out of the date edit onto another editable field it will break and none of the click events will work.

**Comment by braddavistech** [comment]
👍

**Comment by jasehackman** [comment]
👍

**Pull request merged**
